

amcl:
  ros__parameters:
    use_sim_time: false

########################################
# BEHAVIOR TREE NAVIGATOR
########################################
bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_recovery_node_bt_node
      - nav2_smooth_path_action_bt_node

########################################
# CONTROLLER SERVER (Local Planner)
########################################
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]

    # Progress checker
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 10.0

    # Goal checker
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: true

    # Regulated Pure Pursuit Controller
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.18
      max_linear_accel: 0.5
      max_linear_decel: 0.5
      max_angular_accel: 1.5
      lookahead_dist: 0.8
      min_lookahead_dist: 0.6
      max_lookahead_dist: 1.5
      lookahead_time: 1.5
      rotate_to_heading_angular_vel: 0.6
      transform_tolerance: 0.2
      use_velocity_scaled_lookahead_dist: true
      min_approach_linear_velocity: 0.05
      approach_velocity_scaling_dist: 2
      use_collision_detection: true
      max_allowed_time_to_collision_up_to_carrot: 1.0
      use_regulated_linear_velocity_scaling: true
      use_cost_regulated_linear_velocity_scaling: true
      regulated_linear_scaling_min_radius: 0.9
      regulated_linear_scaling_min_speed: 0.25
      use_rotate_to_heading: true
      allow_reversing: true
      rotate_to_heading_min_angle: 0.4
      max_robot_pose_search_dist: 10.0
      use_interpolation: false

########################################
# PLANNER SERVER (Hybrid A*)
########################################
planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["HybridAStar"]

    HybridAStar:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.3
      downsample_costmap: false
      downsampling_factor: 1
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      max_planning_time: 10.0
      motion_model_for_search: "DUBIN"
      angle_quantization_bins: 72
      analytic_expansion_ratio: 3.5
      analytic_expansion_max_length: 3.0
      minimum_turning_radius: 0.6
      reverse_penalty: 2.0
      non_straight_penalty: 1.2
      cost_penalty: 1.0
      retrospective_penalty: 0.015
      lookup_table_size: 20.0
      cache_obstacle_heuristic: true
      smooth_path: true

########################################
# SMOOTHER SERVER (Path Smoothing)
########################################
smoother_server:
  ros__parameters:
    use_sim_time: false
    smoother_plugins: ["simple_smoother"]
    
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true

########################################
# BEHAVIOR SERVER (Recovery Behaviors)
########################################
behavior_server:
  ros__parameters:
    use_sim_time: false
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait", "drive_on_heading"]
    
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.8
    min_rotational_vel: 0.4
    rotational_acc_lim: 2.0

########################################
# VELOCITY SMOOTHER (Smooth Motion)
########################################
velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.21, 0.0, 1.0]
    min_velocity: [-0.21, 0.0, -1.0]
    max_accel: [0.5, 0.0, 1.5]
    max_decel: [-0.5, 0.0, -2.0]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.01, 0.0, 0.01]
    velocity_timeout: 5.0

########################################
# LOCAL COSTMAP (Obstacle Avoidance)
########################################
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 10.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 6
      height: 6
      resolution: 0.05
      robot_radius: 0.5
      plugins: ["obstacle_layer", "inflation_layer"]
      always_send_full_costmap: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.5
          clearing: true
          marking: true
          data_type: "LaserScan"
          obstacle_max_range: 8.0
          obstacle_min_range: 0.6
          raytrace_max_range: 12.0
          raytrace_min_range: 0.1

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6
        cost_scaling_factor: 5.0
        enabled: true

########################################
# GLOBAL COSTMAP (Map from Cartographer)
########################################
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      update_frequency: 3.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      resolution: 0.05
      track_unknown_space: true
      robot_radius: 0.5
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      always_send_full_costmap: true

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        enabled: true
        subscribe_to_updates: true

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.5
          clearing: true
          marking: true
          data_type: "LaserScan"
          obstacle_max_range: 10.0
          obstacle_min_range: 0.6
          raytrace_max_range: 12.0
          raytrace_min_range: 0.1

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6
        cost_scaling_factor: 3.0
        enabled: true

# ########################################
# # COLLISION MONITOR (Safety Layer)
# ########################################
# collision_monitor:
#   ros__parameters:
#     use_sim_time: false
#     base_frame_id: "base_link"
#     odom_frame_id: "odom"
#     cmd_vel_in_topic: "cmd_vel_smoothed"
#     cmd_vel_out_topic: "cmd_vel"
#     transform_tolerance: 0.2
#     source_timeout: 1.0
#     stop_pub_timeout: 2.0
    
#     polygons: ["FootprintApproach"]
    
#     FootprintApproach:
#       type: "polygon"
#       action_type: "approach"
#       footprint_topic: "/local_costmap/published_footprint"
#       time_before_collision: 1.2
#       simulation_time_step: 0.1
#       min_points: 6
#       visualize: true
#       enabled: true
    
#     observation_sources: ["scan"]
    
#     scan:
#       type: "scan"
#       topic: "/scan"
#       min_height: 0.05
#       max_height: 0.6
#       enabled: true

########################################
# WAYPOINT FOLLOWER
########################################
waypoint_follower:
  ros__parameters:
    use_sim_time: false
    loop_rate: 20
    stop_on_failure: true
    waypoint_task_executor_plugin: "wait_at_waypoint"
    
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 0

